### PR TITLE
fixed level 0 display at game start, resized game boxes

### PR DESCRIPTION
**Pull request by inglorious-ratbastard**
Fixes problem with level display of 1 at game start, now displays level 0.
Made game boxes slightly smaller and added simple page title. Still could use more page styling.

### CODE REVIEW

**Comment by adityamangal1** [comment]
Hey @inglorious-ratbastard, thanks for the contribution. Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Comment by kamleshjoshi8102** [comment]
> Fixes problem with level display of 1 at game start, now displays level 0. Made game boxes slightly smaller and added simple page title. Still could use more page styling.

@inglorious-ratbastard Can you provide a ScreenShot of your Page Hosted in your local server or in Github page

**Comment by inglorious-ratbastard** [comment]
Here's a link to my working version 
https://inglorious-ratbastard.github.io/Simon-Game/

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 
Thanks for your valuable contribution : )

**Review by kevalvavaliya — APPROVED** [review]
Looks Good to me ✅

Thanks for your valuable contribution 😎

**Review by harikanani — APPROVED** [review]

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by adityamangal1 — APPROVED** [review]
LGTM

**Pull request merged**
