### PR TITLE
fix: add turn indicator

### PR DESCRIPTION
**Pull request by avinash-tiwari**
Added a message to aware the user memorize or make a move.

### CODE REVIEW

**Review by kevalvavaliya — APPROVED** [review]

**Review by kamleshjoshi8102 — CHANGES_REQUESTED** [review]
Can you  share Changes which you have made in Snapshot : )

**Comment by avinash-tiwari** [comment]
> Can you share Changes which you have made in Snapshot : )

Sure, attaching the screenshots here. @kamleshjoshi8102 
memorize
turn

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM

**Comment by adityamangal1** [comment]
@all-contributors please add @avinash-tiwari for code contribution

**Pull request merged**
